version: '3.9'

services:
  # PostgreSQL para desarrollo (alternativa a MySQL de XAMPP)
  postgres:
    image: postgres:15-alpine
    container_name: laburar_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laburar
      POSTGRES_USER: laburar
      POSTGRES_PASSWORD: laburar123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres:/docker-entrypoint-initdb.d
    networks:
      - laburar_network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: laburar_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis123
    networks:
      - laburar_network

  # Adminer para gestión de PostgreSQL (alternativa a phpMyAdmin)
  adminer:
    image: adminer:latest
    container_name: laburar_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - laburar_network
    depends_on:
      - postgres

  # Redis Commander para gestión de Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: laburar_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis123
    networks:
      - laburar_network
    depends_on:
      - redis

networks:
  laburar_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local