name: 🐛 Bug Report
description: Report a bug to help us improve Laburemos
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🚀
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please check all applicable items
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required information below
          required: true
        - label: I have tested this on the latest version
          required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Production (https://laburemos.com.ar)
        - Local Development
        - Staging
      default: 0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (Next.js)
        - Backend (NestJS API)
        - Database
        - Authentication
        - Admin Panel
        - Payment System
        - Real-time Features
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Paste screenshots or drag & drop files here...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
      default: 2
    validations:
      required: true

  - type: textarea
    id: browser
    attributes:
      label: Browser Information
      description: If this is a frontend issue, please provide browser details
      placeholder: |
        - Browser: Chrome, Firefox, Safari, etc.
        - Version: 
        - Device: Desktop, Mobile, Tablet
        - OS: Windows, macOS, Linux, iOS, Android

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, include relevant error logs or console output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...