@echo off
echo ====================================
echo   LABUREMOS - Local Environment Setup
echo ====================================
echo.

cd /d "D:\Laburar\backend"

REM Backup current .env if exists
if exist .env (
    echo 📄 Backing up current .env to .env.backup
    copy .env .env.backup >nul
)

echo 🔧 Creating local development .env configuration...

REM Create local development .env
(
echo # LABUREMOS Backend - Local Development Configuration
echo # Generated by setup-local-env.bat on %date% %time%
echo.
echo NODE_ENV=development
echo PORT=3001
echo.
echo # Local PostgreSQL Database Configuration
echo DATABASE_URL=postgresql://postgres:postgres@localhost:5432/laburemos
echo.
echo # PostgreSQL Configuration
echo POSTGRES_HOST=localhost
echo POSTGRES_PORT=5432
echo POSTGRES_USER=postgres
echo POSTGRES_PASSWORD=postgres
echo POSTGRES_DB=laburemos
echo.
echo # JWT Configuration - SECURE DEVELOPMENT KEYS
echo JWT_SECRET=laburemos-jwt-secret-local-dev-2025
echo JWT_EXPIRES_IN=7d
echo JWT_REFRESH_SECRET=laburemos-jwt-refresh-secret-local-dev-2025
echo JWT_REFRESH_EXPIRES_IN=30d
echo.
echo # Session Configuration
echo SESSION_SECRET=laburemos-session-secret-local-dev-2025
echo.
echo # CORS Configuration - Local Development
echo CORS_ORIGIN=http://localhost:3000
echo CORS_ORIGINS=http://localhost:3000
echo CORS_CREDENTIALS=true
echo.
echo # Application Configuration
echo APP_NAME=LABUREMOS
echo APP_URL=http://localhost:3001
echo.
echo # Security
echo BCRYPT_ROUNDS=10
echo.
echo # Rate Limiting - Relaxed for development
echo RATE_LIMIT_TTL=60
echo RATE_LIMIT_LIMIT=1000
echo.
echo # File Upload Configuration
echo MAX_FILE_SIZE=10485760
echo ALLOWED_FILE_TYPES=jpg,jpeg,png,gif,pdf,doc,docx,txt
echo UPLOAD_PATH=./uploads
echo.
echo # Logging Configuration
echo LOG_LEVEL=debug
echo LOG_FILE_PATH=./logs/app.log
echo.
echo # Email Configuration - Development ^(Optional^)
echo # SMTP_HOST=smtp.gmail.com
echo # SMTP_PORT=587
echo # SMTP_SECURE=false
echo # SMTP_USER=your_email@gmail.com
echo # SMTP_PASS=your_app_password
echo # EMAIL_FROM=your_email@gmail.com
echo.
echo # AWS Configuration - Development ^(Optional^)
echo # AWS_REGION=us-east-1
echo # AWS_S3_BUCKET=laburemos-files-2025
) > .env

echo ✅ Local .env configuration created

REM Install dependencies if needed
if not exist node_modules (
    echo 📦 Installing backend dependencies...
    npm install
)

echo.
echo 🔍 Verifying Prisma configuration...

REM Check if Prisma schema uses PostgreSQL
findstr /C:"provider = \"postgresql\"" prisma\schema.prisma >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo ✅ Prisma schema configured for PostgreSQL
) else (
    echo ❌ Prisma schema not configured for PostgreSQL
    echo    Please update prisma/schema.prisma datasource to use PostgreSQL
    echo    Change: provider = "mysql" to provider = "postgresql"
)

echo.
echo ====================================
echo   Environment Setup Complete! 🎉
echo ====================================
echo.
echo Next steps:
echo 1. Update Prisma schema to PostgreSQL if needed
echo 2. Run: npm run db:generate
echo 3. Run: npm run db:migrate
echo 4. Run: npm run start:dev
echo.
echo Local development server will be available at:
echo   Backend: http://localhost:3001
echo   API Docs: http://localhost:3001/docs
echo.
pause